# Generated by Django 6.0.6 on 2026-08-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EXPENSE_ADDED', 'Expense Added'), ('INCOME_ADDED', 'Income Added'), ('BUDGET_EVENT', 'Budget Event'), ('BUDGET_INFO', 'Budget Info'), ('BUDGET_WARNING', 'Budget Warning'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('SAVINGS_CREATED', 'Savings Goal Created'), ('SAVINGS_COMPLETED', 'Savings Goal Completed'), ('GOAL_MILESTONE', 'Goal Milestone'), ('SAVINGS_REMINDER', 'Savings Reminder'), ('MONTHLY_REPORT', 'Monthly Report'), ('MOTIVATION', 'Motivational Tip')], default='BUDGET_INFO', max_length=30),
        ),
    ]
