# Generated by Django 6.0.7 on 2026-07-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BUDGET_WARNING', 'Budget Warning'), ('BUDGET_LIMIT', 'Budget Limit Reached'), ('OVERSPENDING', 'Overspending Alert'), ('SAVINGS_REMINDER', 'Savings Reminder'), ('GOAL_MILESTONE', 'Goal Milestone'), ('GOAL_COMPLETED', 'Goal Completed'), ('MONTHLY_REPORT', 'Monthly Report')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
