# Generated by Django 6.0.7 on 2026-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BUDGET_WARNING', 'Budget Warning'), ('BUDGET_HIGH_WARNING', 'Budget High Warning'), ('BUDGET_LIMIT', 'Budget Limit Reached'), ('OVERSPENDING', 'Overspending Alert'), ('SAVINGS_REMINDER', 'Savings Reminder'), ('GOAL_MILESTONE', 'Goal Milestone'), ('GOAL_COMPLETED', 'Goal Completed'), ('MONTHLY_REPORT', 'Monthly Report'), ('BUDGET_CREATED', 'Budget Created'), ('BUDGET_UPDATED', 'Budget Updated'), ('SAVINGS_GOAL_CREATED', 'Savings Goal Created')], max_length=30),
        ),
    ]
