# Generated by Django 5.2.15 on 2026-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_90_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('BILLS', 'Bills'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=50),
        ),
    ]
