# Generated by Django 6.0.6 on 2026-07-21 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_limit',
            new_name='budget_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('bills', 'Bills'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month', 'year')},
        ),
    ]
