# Generated by Django 6.0.7 on 2026-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_alert_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
