# Generated by Django 6.0.6 on 2026-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_monthly_limit_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_90_sent',
            field=models.BooleanField(default=False),
        ),
    ]
