# Generated by Django 5.2.15 on 2026-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_created_at_budget_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_limit',
            new_name='budget_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
