# Generated by Django 6.0.6 on 2026-08-01 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_90_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
    ]
