# Generated by Django 6.0.6 on 2026-07-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
