# Generated by Django 6.0.6 on 2026-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_report_user_expense_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('SHOPPING', 'SHOPPING'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('HEALTHCARE', 'HEALTHCARE'), ('BILLS', 'BILLS'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=50),
        ),
    ]
