# Generated by Django 6.0.6 on 2026-07-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
