# Generated by Django 6.0.6 on 2026-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_delete_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('SHOPPING', 'SHOPPING'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('HEALTHCARE', 'HEALTHCARE'), ('BILLS', 'BILLS'), ('SAVINGS', 'SAVINGS'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=50),
        ),
    ]
