# Generated by Django 6.0.7 on 2026-08-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
            ],
            options={
                'verbose_name': 'Analytics Overview',
                'verbose_name_plural': 'Analytics Overview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expenses.expense',),
        ),
    ]
