# Generated by Django 6.0.6 on 2026-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
