# Generated by Django 6.0.6 on 2026-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Health', 'Health'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=50),
        ),
    ]
