# Generated by Django 6.0.6 on 2026-07-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_expense_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['year', 'month']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date']},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='budget_amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(default=1, help_text='Month of the budget (1-12).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Year of the budget (e.g., 2026).'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the expense.', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the income.', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Unknown', help_text='Source of the income.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the expense was created.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
