# Generated by Django 6.0.6 on 2026-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_notes_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('bills', 'Bills'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=20),
        ),
    ]
