# Generated by Django 6.0.6 on 2026-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_budget_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('SHOPPING', 'SHOPPING'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('HEALTHCARE', 'HEALTHCARE'), ('BILLS', 'BILLS'), ('MISCELLANEOUS', 'MISCELLANEOUS')], help_text='Category for this budget (e.g., FOOD, TRAVEL).', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('SHOPPING', 'SHOPPING'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('HEALTHCARE', 'HEALTHCARE'), ('BILLS', 'BILLS'), ('MISCELLANEOUS', 'MISCELLANEOUS')], help_text='Category of the expense (e.g., FOOD, TRAVEL).', max_length=100),
        ),
    ]
