# Generated by Django 6.0.7 on 2026-07-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Bills', 'Bills'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=30),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
