# Generated by Django 6.0.6 on 2026-07-16 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('SALARY', 'SALARY'), ('POCKET_MONEY', 'POCKET_MONEY'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('FREELANCING', 'FREELANCING'), ('BUSINESS', 'BUSINESS'), ('OTHER', 'OTHER')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('income_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
