# Generated by Django 6.0.6 on 2026-09-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
