# Generated by Django 6.0.6 on 2026-07-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notification.', max_length=200)),
                ('message', models.TextField(help_text='Message body of the notification.')),
                ('notification_type', models.CharField(help_text='Type of notification.', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(help_text='Name of the savings goal.', max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target savings amount.', max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Current saved amount.', max_digits=12)),
                ('target_date', models.DateField(help_text='Target date to complete the goal.')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', help_text='Status of the goal (ACTIVE, COMPLETED, CANCELLED).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', '-created_at'],
            },
        ),
    ]
