# Generated by Django 6.0.6 on 2026-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='MEDIUM', help_text='Priority level of the notification (LOW, MEDIUM, HIGH).', max_length=10),
        ),
    ]
