# Generated by Django 6.0.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='goal_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
