# Generated by Django 6.0.6 on 2026-07-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='is_completed',
        ),
    ]
