# Generated by Django 6.0.6 on 2026-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(default='IN_PROGRESS', max_length=20),
        ),
    ]
