# Generated by Django 6.0.6 on 2026-07-28 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_savingsgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
