# Generated by Django 6.0.6 on 2026-08-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsgoal_created_at_savingsgoal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('EDUCATION', 'Education'), ('EMERGENCY', 'Emergency Fund'), ('HOME', 'Home'), ('VEHICLE', 'Vehicle'), ('GADGETS', 'Gadgets'), ('INVESTMENT', 'Investment'), ('HEALTH', 'Health'), ('RETIREMENT', 'Retirement'), ('OTHER', 'Other')], default='Other', max_length=30),
        ),
    ]
