# Generated by Django 6.0.6 on 2026-07-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_limit_budget_budget_amount_budget_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
    ]
