# Generated by Django 6.0.6 on 2026-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_alert_100_sent_budget_alert_80_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('BILLS', 'Bills'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=20),
        ),
    ]
