# Generated by Django 5.2.15 on 2026-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('premium', 'Premium User'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
