# Generated by Django 6.0.6 on 2026-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('income_added', 'Income Added'), ('expense_added', 'Expense Added'), ('budget_created', 'Budget Created'), ('budget_updated', 'Budget Updated'), ('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('savings_created', 'Savings Goal Created'), ('savings_completed', 'Savings Goal Completed'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
