# Generated by Django 6.0.6 on 2026-08-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('income_added', 'Income Added'), ('income_updated', 'Income Updated'), ('income_deleted', 'Income Deleted'), ('expense_added', 'Expense Added'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('budget_created', 'Budget Created'), ('budget_updated', 'Budget Updated'), ('budget_deleted', 'Budget Deleted'), ('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('savings_created', 'Savings Goal Created'), ('savings_completed', 'Savings Goal Completed'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
