# Generated by Django 5.2.15 on 2026-07-14 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='received_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='income_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('POCKET_MONEY', 'Pocket Money'), ('SCHOLARSHIP', 'Scholarship'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
