# Generated by Django 6.0.6 on 2026-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('POCKET_MONEY', 'POCKET_MONEY'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('FREELANCING', 'FREELANCING'), ('BUSINESS', 'BUSINESS'), ('OTHER', 'OTHER')], default='SALARY', max_length=50),
            preserve_default=False,
        ),
    ]
