# Generated by Django 5.2.15 on 2026-07-15 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('POCKET_MONEY', 'Pocket Money'), ('SCHOLARSHIP', 'Scholarship'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
